name: "Consensus Warn"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    permissions:
      pull-requests: write # For reading the PR and posting comment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: orijtech/consensuswarn@main
        with:
          roots: 'github.com/black/black/v13/app.Black.DeliverTx,github.com/black/black/v13/app.Black.BeginBlocker,github.com/black/black/v13/app.Black.EndBlocker'
